//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 高级人事管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplySalary
    {
        public int Id { get; set; }
        public int s_Id { get; set; }
        public int a_salary { get; set; }
        public string s_department { get; set; }
        public Nullable<int> s_rewAPub { get; set; }
    }
}
