//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 高级人事管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckStaff
    {
        public int c_Id { get; set; }
        public string c_name { get; set; }
        public Nullable<int> c_normal { get; set; }
        public Nullable<int> c_late { get; set; }
    }
}
