//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 高级人事管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int m_Id { get; set; }
        public string m_name { get; set; }
        public string m_production { get; set; }
        public Nullable<int> m_access { get; set; }
    }
}
