//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 高级人事管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int s_Id { get; set; }
        public string s_name { get; set; }
        public string s_gender { get; set; }
        public System.DateTime s_birthday { get; set; }
        public string s_phone { get; set; }
        public string s_email { get; set; }
        public string s_post { get; set; }
        public int s_salary { get; set; }
        public string s_major { get; set; }
        public string s_department { get; set; }
        public string s_username { get; set; }
        public string s_password { get; set; }
    }
}
