//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 高级人事管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStaff
    {
        public int t_id { get; set; }
        public int s_id { get; set; }
        public string s_declar { get; set; }
        public System.DateTime s_startTime { get; set; }
        public System.DateTime s_endTime { get; set; }
        public Nullable<int> s_process { get; set; }
    }
}
